/** Declaration file generated by dts-gen */

export = uri;
interface URL {
    scheme: string;
    authority: string;
}
declare const uri: {
    Uri: {
        afoj: any;
        equalsQueryStr: any;
    };
    uri: {
        checkEncoding(n: URL): string;
        checkFragmentEncoding: any;
        checkQueryEncoding: any;
        checkSegmentEncoding: any;
        checkSegmentsEncoding: any;
        decodeSegments: any;
        decomposeComponents: any;
        encodeFragment: any;
        encodeQuery: any;
        encodeSegment: any;
        encodeSegments: any;
        isSubordinate: any;
        parseQuery: any;
        percentEncode: any;
        recomposeAuthorityComponents: any;
        recomposeComponents: any;
        removeDotSegments: any;
        resolve: any;
    };
};
